src/ShopBundle/Entity/BasketItem.php
<?php
namespace ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="basketitems")
 * @ORM\Entity(repositoryClass="ShopBundle\Repository\BasketItemRepository")
 */
class BasketItem
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Basket", inversedBy="basketItems")
     * @ORM\JoinColumn(name="basket_id", referencedColumnName="id")
     */
    private $basket;

    /**
     * @ORM\ManyToOne(targetEntity="Gadget")
     * @ORM\JoinColumn(name="gadget_id", referencedColumnName="id")
     */
    private $gadget;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount = 0;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set amount
     *
     * @param integer $amount
     *
     * @return BasketItem
     */
    public function setAmount($amount)
    {
        $this->amount += $amount;

        return $this;
    }

    /**
     * Get amount
     *
     * @return integer
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set basket
     *
     * @param \ShopBundle\Entity\Basket $basket
     *
     * @return BasketItem
     */
    public function setBasket(\ShopBundle\Entity\Basket $basket = null)
    {
        $this->basket = $basket;

        return $this;
    }

    /**
     * Get basket
     *
     * @return \ShopBundle\Entity\Basket
     */
    public function getBasket()
    {
        return $this->basket;
    }

    /**
     * Set gadget
     *
     * @param \ShopBundle\Entity\Gadget $gadget
     *
     * @return BasketItem
     */
    public function setGadget(\ShopBundle\Entity\Gadget $gadget = null)
    {
        $this->gadget = $gadget;

        return $this;
    }

    /**
     * Get gadget
     *
     * @return \ShopBundle\Entity\Gadget
     */
    public function getGadget()
    {
        return $this->gadget;
    }

    public function getPrice()
    {
        return $this->getGadget()->getPrice() * $this->getAmount();
    }
}

src/ShopBundle/Controller/SearchController.php
<?php

namespace ShopBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class SearchController extends Controller
{
    public function listAction(Request $request, $page = 1)
    {
        $needle = $this->getNeedle($request);
        $query = $this->get('shop.gadget_repository')->getSearchQuery($needle);
        $gadgets = $this->get('knp_paginator')->paginate($query, $page, $this->getLimit());

        return $this->render('ShopBundle:Search:list.html.twig', compact('gadgets', 'needle'));
    }

    private function getLimit()
    {
        return $this->getParameter('itemsPerPageLimit');
    }

    private function getNeedle(Request $request)
    {
        $needle = $request->get('search');
        $needle = htmlspecialchars($needle, ENT_HTML5);

        return $needle;
    }
}

src/ShopBundle/Resources/views/Search/list.html.twig
{% extends "ShopBundle::layout.html.twig" %}

{% block title %}Search - {{ needle }}{% endblock %}

{% block stylesheets %}
    {% stylesheets '@shop_css' filter='cssrewrite' %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% include 'ShopBundle:_inc:header.html.twig' %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"> {{ gadgets.getTotalItemCount() }} Search results for "{{ needle }}"</div>
            <div class="col-md-1 col-md-offset-5">Sort by:</div>
            <div class="col-md-2">
                <span {% if gadgets.isSorted('g.title') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(gadgets, 'Title', 'g.title') }}</span>
                <span>{{ knp_pagination_sortable(gadgets, 'Price', 'g.price') }}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                {%  for gadget in gadgets %}
                    <div class="col-md-4">
                        <a href="{{ url('shop_gadget_detail', {'id': gadget.id}) }}">
                            <div class="row list-thumb">
                                <div class="col-md-12">
                                    <img src="{{ gadget.image }}" alt="{{ gadget.title }}">
                                </div>
                            </div>
                            <div class="row list-info">
                                <div class="col-md-12">
                                    <span class="gadget-title">{{ gadget.title }}</span>
                                    <span class="gadget-price">{{ gadget.price|price }}</span>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            {% if app.user %}
                <div id="basket-container" class="col-md-3 basket-container">
                    {% include 'ShopBundle:Basket:_inc/list.html.twig' %}
                </div>
            {% endif %}
        </div>
        <div class="row pagination-control">
            {{ knp_pagination_render(gadgets) }}
        </div>
    </div>
{% endblock %}